apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: ghcr.io/<username>/demo-app:latest
          # env:
          # - name: SECRET
          #   valueFrom:
          #     secretKeyRef:
          #       name: my-secret
          #       key: secret-key
          ports:
            - containerPort: 8080